export const UPDATE_DELIVERY_CHOICE = "UPDATE_DELIVERY_CHOICE";
export const UPDATE_OFFER_DETAILS = "UPDATE_OFFER_DETAILS";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const TOGGLE_ERROR = "TOGGLE_ERROR";
