micronaut:
  application:
    name: product-builder-api
  server:
    cors:
      enabled: true
    port: 8081

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/productbuilder`}
    username: ${JDBC_USER:root}
    dialect: MYSQL

jpa:
  default:
    packages-to-scan:
      - 'com.pulgupta'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
